CREATE TABLE `p2p_transaction`.`charity` (
     `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
     `institution_id` INT NOT NULL,
     `user_id` INT NOT NULL,
     `investor` TINYINT NOT NULL,
     `amount` DECIMAL(15,3) NOT NULL,
     `transaction_id` BIGINT NOT NULL,
     `tx_datetime` TIMESTAMP NOT NULL COMMENT '交易時間',
     `receipt_type` TINYINT NOT NULL COMMENT '收據類型 (1:單次紙本)',
     `data` JSON NULL,
     `created_at` TIMESTAMP NOT NULL,
     `created_ip` VARCHAR(15) NOT NULL,
     `updated_at` TIMESTAMP NOT NULL,
     `updated_ip` VARCHAR(15) NOT NULL,
     PRIMARY KEY (`id`, `created_at`),
     INDEX `idx` (`institution_id` ASC, `user_id` ASC, `tx_datetime` ASC),
     INDEX `idx2` (`transaction_id` ASC))
    PARTITION BY RANGE( UNIX_TIMESTAMP(created_at))(
    PARTITION from_2022_or_less VALUES LESS THAN (UNIX_TIMESTAMP('2022-01-01 00:00:00')),
    PARTITION from_2023 VALUES LESS THAN (UNIX_TIMESTAMP('2023-01-01 00:00:00')),
    PARTITION from_2024 VALUES LESS THAN (UNIX_TIMESTAMP('2024-01-01 00:00:00')),
    PARTITION from_2025 VALUES LESS THAN (UNIX_TIMESTAMP('2025-01-01 00:00:00')),
    PARTITION from_2026 VALUES LESS THAN (UNIX_TIMESTAMP('2026-01-01 00:00:00')),
    PARTITION from_2027_and_up VALUES LESS THAN MAXVALUE);

CREATE TABLE `p2p_user`.`charity_institution` (
      `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      `judicial_person_id` INT NOT NULL,
      `virtual_account` VARCHAR(25) NOT NULL,
      `alias` VARCHAR(45) NOT NULL,
      `name` VARCHAR(50) NOT NULL,
      `min_amount` DECIMAL(15,3) NOT NULL,
      `max_amount` DECIMAL(15,3) NOT NULL,
      `CoA_content` LONGTEXT NULL COMMENT '感謝狀合約格式',
      `agreement_id` INT NOT NULL DEFAULT 0,
      `data` JSON NULL,
      `status` TINYINT NOT NULL DEFAULT 1 COMMENT '0: 停用, 1:啟用',
      `created_at` TIMESTAMP NOT NULL,
      `created_ip` VARCHAR(15) NOT NULL,
      `created_admin_id` INT(11) NOT NULL DEFAULT '0',
      `updated_at` TIMESTAMP NOT NULL,
      `updated_ip` VARCHAR(15) NOT NULL,
      `updated_admin_id` INT(11) NOT NULL DEFAULT '0',
      PRIMARY KEY (`id`),
      INDEX `idx` (`alias` ASC));
