CREATE TABLE `p2p_user`.`user_qrcode` (
      `id` BIGINT NOT NULL AUTO_INCREMENT,
      `user_id` INT NOT NULL DEFAULT 0,
      `alias` VARCHAR(45) NOT NULL DEFAULT '',
      `promote_code` VARCHAR(25) NOT NULL,
      `status` TINYINT NOT NULL DEFAULT 1 COMMENT '0: 已停用, 1:有效',
      `contract_id` INT NOT NULL DEFAULT 0,
      `start_time` TIMESTAMP NOT NULL COMMENT '合約開始時間',
      `end_time` TIMESTAMP NOT NULL COMMENT '合約結束時間',
      `handle_time` TIMESTAMP NULL COMMENT '最近一次結算時間',
      `settlementing` TINYINT NOT NULL DEFAULT 0 COMMENT '0: 可結算, 1:正在結算',
      `settings` JSON NOT NULL,
      `created_at` TIMESTAMP NOT NULL,
      `created_ip` VARCHAR(15) NOT NULL,
      `updated_at` TIMESTAMP NOT NULL,
      `updated_ip` VARCHAR(15) NOT NULL,
      PRIMARY KEY (`id`),
      INDEX `idx1` (`promote_code` ASC, `user_id` ASC),
      INDEX `idx2` (`start_time` ASC, `end_time` ASC));

CREATE TABLE `p2p_user`.`qrcode_setting` (
     `id` INT NOT NULL AUTO_INCREMENT,
     `alias` VARCHAR(45) NOT NULL,
     `description` VARCHAR(45) NOT NULL DEFAULT '',
     `status` TINYINT NOT NULL DEFAULT 1 COMMENT '0: 停用, 1:有效',
     `start_time` TIMESTAMP NOT NULL COMMENT '活動開始時間',
     `end_time` TIMESTAMP NOT NULL COMMENT '活動結束時間',
     `settings` JSON NOT NULL,
     `length` TINYINT NOT NULL,
     `prefix` VARCHAR(15) NOT NULL DEFAULT '',
     `created_at` TIMESTAMP NOT NULL,
     `created_ip` VARCHAR(15) NOT NULL,
     `created_admin_id` INT NOT NULL DEFAULT 0,
     `updated_at` TIMESTAMP NOT NULL,
     `updated_ip` VARCHAR(15) NOT NULL,
     `updated_admin_id` INT NOT NULL DEFAULT 0,
     PRIMARY KEY (`id`),
     UNIQUE INDEX `alias_UNIQUE` (`alias` ASC),
     INDEX `idx1` (`end_time` ASC, `status` ASC),
     INDEX `idx2` (`alias` ASC, `status` ASC));

CREATE TABLE `p2p_transaction`.`qrcode_reward` (
   `id` INT NOT NULL AUTO_INCREMENT,
   `user_qrcode_id` BIGINT NOT NULL,
   `status` TINYINT NOT NULL DEFAULT 0 COMMENT '0: 已刪除, 1:尚未處理, 2:已處理',
   `start_time` TIMESTAMP NOT NULL COMMENT '結算起始日期',
   `end_time` TIMESTAMP NOT NULL COMMENT '結算結束日期',
   `amount` DECIMAL(12,3) NOT NULL,
   `settlement_time` TIMESTAMP NULL DEFAULT 0 COMMENT '獎金入帳時間',
   `json_data` JSON NOT NULL,
   `created_at` TIMESTAMP NOT NULL,
   `created_ip` VARCHAR(15) NOT NULL,
   `updated_at` TIMESTAMP NOT NULL,
   `updated_ip` VARCHAR(15) NOT NULL,
   PRIMARY KEY (`id`),
   INDEX `idx1` (`user_qrcode_id` ASC, `settlement_time` ASC),
   INDEX `idx2` (`status` ASC, `start_time` ASC, `end_time` ASC));