CREATE TABLE `p2p_loan`.`credit_sheet` (
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `target_id` BIGINT(20) NOT NULL,
    `credit_id` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '對應的核可額度編號',
    `certification_list` JSON NOT NULL COMMENT '核准額度當下的已通過認證項目編號',
    `relation` JSON NOT NULL COMMENT '關係戶資料',
    `unused_credit_line` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '可動用額度',
    `total_line` BIGINT NOT NULL DEFAULT 0 COMMENT '額度總計 (以日合併計算)',
    `line_expired_at` TIMESTAMP NOT NULL COMMENT '額度到期日',
    `interest_type` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '計息方式 (1:按月計息-本息均攤, 2:按月繳息-本金到期一次清償)\n還款方式也是依照此欄位判斷',
    `drawdown_type` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '動撥方式  (1: 一次動用, 2:分次動用, 3:循還動用)',
    `review_level` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '最終核可層級',
    `credit_category` TINYINT NOT NULL DEFAULT 0 COMMENT '1: 新案, 2:增貸, 3:改貸, 4:產品轉換',
    `product_category` JSON NULL COMMENT '產品類別(多個)',
    `note` VARCHAR(300) NOT NULL DEFAULT '' COMMENT '其他說明',
    `status` TINYINT NOT NULL DEFAULT 0 COMMENT '0: 尚未核可, 1:已完成',
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `created_ip` VARCHAR(15) NOT NULL,
    `updated_ip` VARCHAR(15) NOT NULL,
    PRIMARY KEY (`id`, `created_at`),
    INDEX `target_credit` (`target_id` ASC, `credit_id` ASC),
    INDEX `createdat_status` (`created_at` ASC, `status` ASC),
    INDEX `status_target_credit` (`status` ASC, `target_id` ASC, `credit_id` ASC),
    INDEX `target_unusedcredit` (`target_id` ASC, `unused_credit_line` ASC),
    INDEX `target_totalline` (`target_id` ASC, `total_line` ASC)) PARTITION BY RANGE( UNIX_TIMESTAMP(created_at) ) (
     PARTITION from_2022_or_less VALUES LESS THAN (UNIX_TIMESTAMP('2022-01-01 00:00:00')),
     PARTITION from_2023 VALUES LESS THAN (UNIX_TIMESTAMP('2023-01-01 00:00:00')),
     PARTITION from_2024 VALUES LESS THAN (UNIX_TIMESTAMP('2024-01-01 00:00:00')),
     PARTITION from_2025 VALUES LESS THAN (UNIX_TIMESTAMP('2025-01-01 00:00:00')),
     PARTITION from_2026 VALUES LESS THAN (UNIX_TIMESTAMP('2026-01-01 00:00:00')),
 	PARTITION from_2027 VALUES LESS THAN (UNIX_TIMESTAMP('2027-01-01 00:00:00')),
     PARTITION from_2028_and_up VALUES LESS THAN MAXVALUE);

CREATE TABLE `p2p_loan`.`credit_sheet_review` (
   `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
   `credit_sheet_id` BIGINT UNSIGNED NOT NULL,
   `admin_id` INT(11) UNSIGNED NOT NULL,
   `name` VARCHAR(45) NOT NULL,
   `opinion` VARCHAR(200) NOT NULL DEFAULT '',
   `score` INT NOT NULL,
   `group` INT NOT NULL,
   `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   `created_ip` VARCHAR(15) NOT NULL,
   `updated_ip` VARCHAR(15) NOT NULL,
   PRIMARY KEY (`id`, `created_at`),
   INDEX `index2` (`credit_sheet_id` DESC),
   INDEX `index3` (`credit_sheet_id` DESC, `group` DESC)) PARTITION BY RANGE( UNIX_TIMESTAMP(created_at) ) (
    PARTITION from_2022_or_less VALUES LESS THAN (UNIX_TIMESTAMP('2022-01-01 00:00:00')),
    PARTITION from_2023 VALUES LESS THAN (UNIX_TIMESTAMP('2023-01-01 00:00:00')),
    PARTITION from_2024 VALUES LESS THAN (UNIX_TIMESTAMP('2024-01-01 00:00:00')),
    PARTITION from_2025 VALUES LESS THAN (UNIX_TIMESTAMP('2025-01-01 00:00:00')),
    PARTITION from_2026 VALUES LESS THAN (UNIX_TIMESTAMP('2026-01-01 00:00:00')),
	PARTITION from_2027 VALUES LESS THAN (UNIX_TIMESTAMP('2027-01-01 00:00:00')),
    PARTITION from_2028_and_up VALUES LESS THAN MAXVALUE);
