# 部門
TRUNCATE table p2p_admin.`groups`;
INSERT INTO p2p_admin.`groups` (id, division, department, `position`, created_at, created_ip, created_admin_id, updated_at, updated_ip, updated_admin_id) VALUES(1, '超級管理員', '超級管理員', 1, '2022-06-08 07:10:41', '', 72, '2022-06-08 07:10:41', '', 72);
INSERT INTO p2p_admin.`groups` (id, division, department, `position`, created_at, created_ip, created_admin_id, updated_at, updated_ip, updated_admin_id) VALUES(2, '慈善公益', '慈善公益', 2, '2022-06-08 07:11:41', '', 72, '2022-06-08 07:11:41', '', 72);
INSERT INTO p2p_admin.`groups` (id, division, department, `position`, created_at, created_ip, created_admin_id, updated_at, updated_ip, updated_admin_id) VALUES(3, '慈善公益', '慈善公益', 3, '2022-06-08 07:12:44', '', 72, '2022-06-08 07:12:44', '', 72);
INSERT INTO p2p_admin.`groups` (id, division, department, `position`, created_at, created_ip, created_admin_id, updated_at, updated_ip, updated_admin_id) VALUES(4, '風險管理', '授信審查', 2, '2022-06-09 02:44:05', '', 72, '2022-06-09 02:44:05', '', 72);
INSERT INTO p2p_admin.`groups` (id, division, department, `position`, created_at, created_ip, created_admin_id, updated_at, updated_ip, updated_admin_id) VALUES(5, '風險管理', '授信審查', 3, '2022-06-09 02:50:16', '', 72, '2022-06-09 02:50:16', '', 72);
INSERT INTO p2p_admin.`groups` (id, division, department, `position`, created_at, created_ip, created_admin_id, updated_at, updated_ip, updated_admin_id) VALUES(6, '風險管理', '貸後管理', 2, '2022-06-09 03:10:46', '', 72, '2022-06-09 03:10:46', '', 72);
INSERT INTO p2p_admin.`groups` (id, division, department, `position`, created_at, created_ip, created_admin_id, updated_at, updated_ip, updated_admin_id) VALUES(7, '風險管理', '貸後管理', 3, '2022-06-09 03:11:39', '', 72, '2022-06-09 03:11:39', '', 72);
INSERT INTO p2p_admin.`groups` (id, division, department, `position`, created_at, created_ip, created_admin_id, updated_at, updated_ip, updated_admin_id) VALUES(8, '風險管理', '客服管理', 2, '2022-06-09 03:12:53', '', 72, '2022-06-09 03:12:53', '', 72);
INSERT INTO p2p_admin.`groups` (id, division, department, `position`, created_at, created_ip, created_admin_id, updated_at, updated_ip, updated_admin_id) VALUES(9, '風險管理', '客服管理', 3, '2022-06-09 03:13:40', '', 72, '2022-06-09 03:13:40', '', 72);
INSERT INTO p2p_admin.`groups` (id, division, department, `position`, created_at, created_ip, created_admin_id, updated_at, updated_ip, updated_admin_id) VALUES(10, '財會稽核', '財會稽核', 2, '2022-06-09 03:14:35', '', 72, '2022-06-09 03:14:35', '', 72);
INSERT INTO p2p_admin.`groups` (id, division, department, `position`, created_at, created_ip, created_admin_id, updated_at, updated_ip, updated_admin_id) VALUES(11, '財會稽核', '財會稽核', 3, '2022-06-09 03:15:15', '', 72, '2022-06-09 03:15:15', '', 72);
INSERT INTO p2p_admin.`groups` (id, division, department, `position`, created_at, created_ip, created_admin_id, updated_at, updated_ip, updated_admin_id) VALUES(12, '市場行銷', '行銷設計', 2, '2022-06-09 03:16:45', '', 72, '2022-06-09 03:16:45', '', 72);
INSERT INTO p2p_admin.`groups` (id, division, department, `position`, created_at, created_ip, created_admin_id, updated_at, updated_ip, updated_admin_id) VALUES(13, '市場行銷', '行銷設計', 3, '2022-06-09 03:16:45', '', 72, '2022-06-09 03:16:45', '', 72);
INSERT INTO p2p_admin.`groups` (id, division, department, `position`, created_at, created_ip, created_admin_id, updated_at, updated_ip, updated_admin_id) VALUES(14, '市場行銷', '行銷企劃', 2, '2022-06-09 03:16:45', '', 72, '2022-06-09 03:16:45', '', 72);
INSERT INTO p2p_admin.`groups` (id, division, department, `position`, created_at, created_ip, created_admin_id, updated_at, updated_ip, updated_admin_id) VALUES(15, '市場行銷', '行銷企劃', 3, '2022-06-09 03:16:45', '', 72, '2022-06-09 03:16:45', '', 72);
INSERT INTO p2p_admin.`groups` (id, division, department, `position`, created_at, created_ip, created_admin_id, updated_at, updated_ip, updated_admin_id) VALUES(16, '市場行銷', '業務行銷', 2, '2022-06-09 03:16:45', '', 72, '2022-06-09 03:16:45', '', 72);
INSERT INTO p2p_admin.`groups` (id, division, department, `position`, created_at, created_ip, created_admin_id, updated_at, updated_ip, updated_admin_id) VALUES(17, '市場行銷', '業務行銷', 3, '2022-06-09 03:16:45', '', 72, '2022-06-09 03:16:45', '', 72);
INSERT INTO p2p_admin.`groups` (id, division, department, `position`, created_at, created_ip, created_admin_id, updated_at, updated_ip, updated_admin_id) VALUES(18, '系統科技', '系統科技', 2, '2022-06-09 03:16:45', '', 72, '2022-06-09 03:16:45', '', 72);
INSERT INTO p2p_admin.`groups` (id, division, department, `position`, created_at, created_ip, created_admin_id, updated_at, updated_ip, updated_admin_id) VALUES(19, '系統科技', '系統科技', 3, '2022-06-09 03:16:45', '', 72, '2022-06-09 03:16:45', '', 72);
# 部門權限
TRUNCATE table p2p_admin.`group_permission`;
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Account', 'daily_report', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Account', 'estatement', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Account', 'index', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Account', 'passbook_report', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Admin', 'admin_permission_list', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Admin', 'group_permission_list', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Admin', 'index', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Admin', 'permission_grant_list', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Admin', 'permission_search', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Agreement', 'index', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'AntiFraud', 'index', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'AntiFraud', 'list', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Article', 'index', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Article', 'news', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Certification', 'difficult_word_list', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Certification', 'index', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Certification', 'user_certification_list', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Charity', 'index', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Contact', 'certifications', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Contact', 'index', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Contact', 'send_email', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Contract', 'index', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Creditmanagement', 'index', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Judicialperson', 'cooperation_apply', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Judicialperson', 'cooperation_management', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Judicialperson', 'juridical_apply', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Judicialperson', 'juridical_management', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Ocr', 'index', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Partner', 'index', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Partner', 'partner_type', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Passbook', 'index', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Passbook', 'unknown_funds', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Passbook', 'user_bankaccount_list', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Passbook', 'withdraw_list', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Passbook', 'withdraw_waiting', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'PostLoan', 'deduct', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'PostLoan', 'legal_doc', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Product', 'index', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Risk', 'black_list', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Risk', 'credit', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Risk', 'credit_management', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Risk', 'investor', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Risk', 'juridical_person', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Risk', 'natural_person', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Sales', 'bonus_report', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Sales', 'index', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Sales', 'loan_overview', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Sales', 'promote_list', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Sales', 'promote_reward_list', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Sales', 'qrcode_contracts', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Sales', 'qrcode_projects', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Sales', 'register_report', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Sales', 'sales_report', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Sales', 'valuable_report', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Scraper', 'index', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Target', 'finished', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Target', 'index', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Target', 'order_target', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Target', 'prepayment', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Target', 'repayment', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Target', 'repayment_delayed', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Target', 'waiting_approve_order_transfer', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Target', 'waiting_bidding', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Target', 'waiting_evaluation', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Target', 'waiting_loan', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Target', 'waiting_signing', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Target', 'waiting_verify', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Transfer', 'bidding', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Transfer', 'index', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Transfer', 'obligations', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Transfer', 'waiting_transfer', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'Transfer', 'waiting_transfer_success', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'User', 'blocked_users', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(1, 'User', 'index', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(2, 'Charity', 'index', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(3, 'Charity', 'index', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'AntiFraud', 'index', 7);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'AntiFraud', 'list', 5);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'Certification', 'index', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'Certification', 'user_certification_list', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'Judicialperson', 'cooperation_apply', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'Judicialperson', 'cooperation_management', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'Judicialperson', 'juridical_apply', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'Judicialperson', 'juridical_management', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'Partner', 'index', 7);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'Partner', 'partner_type', 5);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'Risk', 'black_list', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'Risk', 'credit', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'Risk', 'credit_management', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'Risk', 'investor', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'Risk', 'juridical_person', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'Risk', 'natural_person', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'Sales', 'bonus_report', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'Sales', 'index', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'Sales', 'loan_overview', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'Sales', 'register_report', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'Sales', 'sales_report', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'Sales', 'valuable_report', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'Scraper', 'index', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'Target', 'finished', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'Target', 'index', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'Target', 'order_target', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'Target', 'prepayment', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'Target', 'repayment', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'Target', 'repayment_delayed', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'Target', 'waiting_approve_order_transfer', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'Target', 'waiting_bidding', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'Target', 'waiting_evaluation', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'Target', 'waiting_loan', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'Target', 'waiting_signing', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'Target', 'waiting_verify', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'User', 'blocked_users', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'User', 'edit', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(4, 'User', 'index', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'AntiFraud', 'index', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'AntiFraud', 'list', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'Certification', 'index', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'Certification', 'user_certification_list', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'Judicialperson', 'cooperation_apply', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'Judicialperson', 'cooperation_management', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'Judicialperson', 'juridical_apply', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'Judicialperson', 'juridical_management', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'Partner', 'index', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'Partner', 'partner_type', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'Risk', 'black_list', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'Risk', 'credit', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'Risk', 'credit_management', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'Risk', 'investor', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'Risk', 'juridical_person', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'Risk', 'natural_person', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'Sales', 'bonus_report', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'Sales', 'index', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'Sales', 'loan_overview', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'Sales', 'register_report', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'Sales', 'sales_report', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'Sales', 'valuable_report', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'Scraper', 'index', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'Target', 'finished', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'Target', 'index', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'Target', 'order_target', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'Target', 'prepayment', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'Target', 'repayment', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'Target', 'repayment_delayed', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'Target', 'waiting_approve_order_transfer', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'Target', 'waiting_bidding', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'Target', 'waiting_evaluation', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'Target', 'waiting_loan', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'Target', 'waiting_signing', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'Target', 'waiting_verify', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'User', 'blocked_users', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'User', 'edit', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(5, 'User', 'index', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(6, 'PostLoan', 'deduct', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(6, 'PostLoan', 'legal_doc', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(6, 'Target', 'finished', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(6, 'Target', 'prepayment', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(6, 'Target', 'repayment', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(6, 'Target', 'repayment_delayed', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(7, 'PostLoan', 'deduct', 15);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(7, 'PostLoan', 'legal_doc', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(7, 'Target', 'finished', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(7, 'Target', 'prepayment', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(7, 'Target', 'repayment', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(7, 'Target', 'repayment_delayed', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(8, 'Contact', 'certifications', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(8, 'Contact', 'index', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(8, 'Contact', 'send_email', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(9, 'Contact', 'certifications', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(9, 'Contact', 'index', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(9, 'Contact', 'send_email', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(10, 'Account', 'daily_report', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(10, 'Account', 'estatement', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(10, 'Account', 'index', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(10, 'Account', 'passbook_report', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(10, 'Certification', 'difficult_word_list', 7);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(10, 'Charity', 'index', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(10, 'Contact', 'certifications', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(10, 'Contact', 'index', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(10, 'Contact', 'send_email', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(10, 'Passbook', 'index', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(10, 'Passbook', 'unknown_funds', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(10, 'Passbook', 'user_bankaccount_list', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(10, 'Passbook', 'withdraw_list', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(10, 'Passbook', 'withdraw_waiting', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(10, 'Sales', 'promote_list', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(10, 'Sales', 'promote_reward_list', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(10, 'Target', 'finished', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(10, 'Target', 'index', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(10, 'Target', 'prepayment', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(10, 'Target', 'repayment', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(10, 'Target', 'repayment_delayed', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(10, 'Target', 'waiting_loan', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(10, 'Transfer', 'bidding', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(10, 'Transfer', 'index', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(10, 'Transfer', 'obligations', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(10, 'Transfer', 'waiting_transfer', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(10, 'Transfer', 'waiting_transfer_success', 3);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(11, 'Account', 'daily_report', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(11, 'Account', 'estatement', 1);
INSERT INTO p2p_admin.group_permission (group_id, model_key, submodel_key, action_type) VALUES(11, 'Account', 'index', 1);
# 管理員
UPDATE p2p_admin.admins SET `group_id`=0, `permission_status`=0;
UPDATE p2p_admin.admins SET `group_id`=1, `permission_status`=1 WHERE `id`=1;
UPDATE p2p_admin.admins SET `group_id`=4, `permission_status`=1 WHERE `email` IN ('frank@influxfin.com', 'qqq0123@influxfin.com');
UPDATE p2p_admin.admins SET `group_id`=7, `permission_status`=1 WHERE `email` IN ('timlee@influxfin.com');
UPDATE p2p_admin.admins SET `group_id`=11, `permission_status`=1 WHERE `email` IN ('katia@influxfin.com');
UPDATE p2p_admin.admins SET `group_id`=11, `permission_status`=1 WHERE `email` IN ('mori@influxfin.com');
UPDATE p2p_admin.admins SET `group_id`=18, `permission_status`=1 WHERE `email` IN ('wayne@influxfin.com');
UPDATE p2p_admin.admins SET `group_id`=19, `permission_status`=1 WHERE `email` IN ('nabroux@influxfin.com');
# 管理員權限
TRUNCATE table p2p_admin.`admin_permission`;
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT `id`, 'Sales', 'bonus_report', 1 FROM `p2p_admin`.`admins` WHERE `email`='mori@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT `id`, 'Sales', 'qrcode_contracts', 1 FROM `p2p_admin`.`admins` WHERE `email`='mori@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT `id`, 'Sales', 'qrcode_projects', 1 FROM `p2p_admin`.`admins` WHERE `email`='mori@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT `id`, 'Sales', 'register_report', 1 FROM `p2p_admin`.`admins` WHERE `email`='mori@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT `id`, 'Target', 'waiting_bidding', 1 FROM `p2p_admin`.`admins` WHERE `email`='mori@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Transfer', 'bidding', 1 FROM p2p_admin.admins a WHERE a.email='frank@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Transfer', 'index', 1 FROM p2p_admin.admins a WHERE a.email='frank@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Transfer', 'obligations', 1 FROM p2p_admin.admins a WHERE a.email='frank@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Transfer', 'waiting_transfer', 1 FROM p2p_admin.admins a WHERE a.email='frank@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Transfer', 'waiting_transfer_success', 1 FROM p2p_admin.admins a WHERE a.email='frank@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Sales', 'promote_list', 1 FROM p2p_admin.admins a WHERE a.email='frank@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Sales', 'qrcode_projects', 3 FROM p2p_admin.admins a WHERE a.email='frank@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Account', 'daily_report', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Account', 'estatement', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Account', 'index', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Account', 'passbook_report', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Agreement', 'index', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'AntiFraud', 'index', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'AntiFraud', 'list', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Article', 'index', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Article', 'news', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Certification', 'difficult_word_list', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Certification', 'index', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Certification', 'user_certification_list', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Charity', 'index', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Contact', 'index', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Contact', 'send_email', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Contract', 'index', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Creditmanagement', 'index', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Judicialperson', 'cooperation_apply', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Judicialperson', 'cooperation_management', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Judicialperson', 'juridical_apply', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Judicialperson', 'juridical_management', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Ocr', 'index', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Partner', 'index', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Partner', 'partner_type', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Passbook', 'index', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Passbook', 'unknown_funds', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Passbook', 'user_bankaccount_list', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Passbook', 'withdraw_list', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Passbook', 'withdraw_waiting', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'PostLoan', 'deduct', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'PostLoan', 'legal_doc', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Product', 'index', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Risk', 'black_list', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Risk', 'credit', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Risk', 'credit_management', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Risk', 'investor', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Risk', 'juridical_person', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Risk', 'natural_person', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Sales', 'bonus_report', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Sales', 'index', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Sales', 'loan_overview', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Sales', 'promote_list', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Sales', 'promote_reward_list', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Sales', 'qrcode_contracts', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Sales', 'qrcode_projects', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Sales', 'register_report', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Sales', 'sales_report', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Sales', 'valuable_report', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Target', 'finished', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Target', 'index', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Target', 'order_target', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Target', 'prepayment', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Target', 'repayment', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Target', 'repayment_delayed', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Target', 'waiting_approve_order_transfer', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Target', 'waiting_bidding', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Target', 'waiting_evaluation', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Target', 'waiting_loan', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Target', 'waiting_signing', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Target', 'waiting_verify', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Transfer', 'bidding', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Transfer', 'index', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Transfer', 'obligations', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Transfer', 'waiting_transfer', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Transfer', 'waiting_transfer_success', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'User', 'blocked_users', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'User', 'index', 1 FROM p2p_admin.admins a WHERE a.email='nabroux@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Account', 'daily_report', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Account', 'estatement', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Account', 'index', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Account', 'passbook_report', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Admin', 'admin_permission_list', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Admin', 'index', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Agreement', 'index', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'AntiFraud', 'index', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'AntiFraud', 'list', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Article', 'index', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Article', 'news', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Certification', 'difficult_word_list', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Certification', 'index', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Certification', 'user_certification_list', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Charity', 'index', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Contact', 'index', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Contact', 'send_email', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Contract', 'index', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Creditmanagement', 'index', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Judicialperson', 'cooperation_apply', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Judicialperson', 'cooperation_management', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Judicialperson', 'juridical_apply', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Judicialperson', 'juridical_management', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Ocr', 'index', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Partner', 'index', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Partner', 'partner_type', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Passbook', 'index', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Passbook', 'unknown_funds', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Passbook', 'user_bankaccount_list', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Passbook', 'withdraw_list', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Passbook', 'withdraw_waiting', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'PostLoan', 'deduct', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'PostLoan', 'legal_doc', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Product', 'index', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Risk', 'black_list', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Risk', 'credit', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Risk', 'credit_management', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Risk', 'investor', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Risk', 'juridical_person', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Risk', 'natural_person', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Sales', 'bonus_report', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Sales', 'index', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Sales', 'loan_overview', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Sales', 'promote_list', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Sales', 'promote_reward_list', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Sales', 'qrcode_contracts', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Sales', 'qrcode_projects', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Sales', 'register_report', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Sales', 'sales_report', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Sales', 'valuable_report', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Target', 'finished', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Target', 'index', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Target', 'order_target', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Target', 'prepayment', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Target', 'repayment', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Target', 'repayment_delayed', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Target', 'waiting_approve_order_transfer', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Target', 'waiting_bidding', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Target', 'waiting_evaluation', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Target', 'waiting_loan', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Target', 'waiting_signing', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Target', 'waiting_verify', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Transfer', 'bidding', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Transfer', 'index', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Transfer', 'obligations', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Transfer', 'waiting_transfer', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Transfer', 'waiting_transfer_success', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'User', 'blocked_users', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'User', 'index', 1 FROM p2p_admin.admins a WHERE a.email='wayne@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Contact', 'certifications', 1 FROM p2p_admin.admins a WHERE email='qqq0123@influxfin.com ';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Contact', 'index', 3 FROM p2p_admin.admins a WHERE email='qqq0123@influxfin.com ';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Contact', 'send_email', 3 FROM p2p_admin.admins a WHERE email='qqq0123@influxfin.com ';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Sales', 'promote_list', 1 FROM p2p_admin.admins a WHERE email='qqq0123@influxfin.com ';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Sales', 'qrcode_projects', 3 FROM p2p_admin.admins a WHERE email='qqq0123@influxfin.com ';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Certification', 'index', 1 FROM p2p_admin.admins a WHERE a.email='katia@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Certification', 'user_certification_list', 3 FROM p2p_admin.admins a WHERE a.email='katia@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'PostLoan', 'deduct', 15 FROM p2p_admin.admins a WHERE a.email='katia@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'PostLoan', 'legal_doc', 3 FROM p2p_admin.admins a WHERE a.email='katia@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Risk', 'black_list', 1 FROM p2p_admin.admins a WHERE a.email='katia@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Risk', 'credit', 1 FROM p2p_admin.admins a WHERE a.email='katia@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Risk', 'investor', 3 FROM p2p_admin.admins a WHERE a.email='katia@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Risk', 'juridical_person', 3 FROM p2p_admin.admins a WHERE a.email='katia@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Risk', 'natural_person', 3 FROM p2p_admin.admins a WHERE a.email='katia@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Target', 'order_target', 1 FROM p2p_admin.admins a WHERE a.email='katia@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Target', 'waiting_approve_order_transfer', 1 FROM p2p_admin.admins a WHERE a.email='katia@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Target', 'waiting_bidding', 1 FROM p2p_admin.admins a WHERE a.email='katia@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Target', 'waiting_evaluation', 1 FROM p2p_admin.admins a WHERE a.email='katia@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Target', 'waiting_signing', 1 FROM p2p_admin.admins a WHERE a.email='katia@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Target', 'waiting_verify', 3 FROM p2p_admin.admins a WHERE a.email='katia@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'User', 'blocked_users', 3 FROM p2p_admin.admins a WHERE a.email='katia@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'User', 'index', 3 FROM p2p_admin.admins a WHERE a.email='katia@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Contact', 'certifications', 1 FROM p2p_admin.admins a WHERE a.email='timlee@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Contact', 'index', 3 FROM p2p_admin.admins a WHERE a.email='timlee@influxfin.com';
INSERT INTO p2p_admin.admin_permission (admin_id, model_key, submodel_key, action_type) SELECT id, 'Contact', 'send_email', 3 FROM p2p_admin.admins a WHERE a.email='timlee@influxfin.com';
