CREATE TABLE `p2p_user`.`user_subcode` (
   `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
   `user_id` INT(11) NOT NULL DEFAULT '0',
   `alias` VARCHAR(70) NOT NULL DEFAULT '' COMMENT '暱稱別名',
   `registered_phone` VARCHAR(25) NOT NULL DEFAULT '' COMMENT '登記subcode的手機',
   `user_qrcode_id` VARCHAR(45) NOT NULL DEFAULT '',
   `promote_code` VARCHAR(25) NOT NULL,
   `status` TINYINT(4) NOT NULL DEFAULT '1' COMMENT '0: 已停用, 1:有效',
   `start_time` TIMESTAMP NOT NULL COMMENT '合約開始時間',
   `end_time` TIMESTAMP NULL COMMENT '合約結束時間',
   `last_handle_time` TIMESTAMP NULL COMMENT '最近一次處理時間',
   `settings` JSON NOT NULL,
   `created_at` TIMESTAMP NOT NULL,
   `created_ip` VARCHAR(15) NOT NULL,
   `updated_at` TIMESTAMP NOT NULL,
   `updated_ip` VARCHAR(15) NOT NULL,
   PRIMARY KEY (`id`),
   INDEX `user_idx` USING BTREE (`user_id`, `registered_phone`),
   INDEX `user_qrcode_idx` USING BTREE (`user_qrcode_id`),
   INDEX `status_idx` USING BTREE (`status`, `start_time`, `end_time`),
   INDEX `promote_code_idx` USING BTREE (`promote_code`));
