name: Build and Deploy

on:
  push:
    branches:
      - dev
      - test-devops
  pull_request:
    branches:
      - '*'
  release:
    types: [created]

jobs:
  build-and-deploy-dev:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/test-devops' || github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.base.ref == 'dev' || github.event.pull_request.base.ref == 'test-devops')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and Push Docker Image (Dev)
      run: |
        short_sha=$(echo "${{ github.sha }}" | cut -c1-7)
        docker build -t 425212047113.dkr.ecr.ap-northeast-1.amazonaws.com/influx-website:$short_sha .
        docker push 425212047113.dkr.ecr.ap-northeast-1.amazonaws.com/influx-website:$short_sha

    - name: Update Kustomize Deploy (Dev)
      run: |
        git fetch
        git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
        git fetch origin
        git switch devops

        sed -E -i "s|(image:[^:]+).*|image:\ gcr.io/vrcam-dev-5a815/viewer-backend-v3/viewer-backend-v3-dev:${{ github.sha::7 }}|g" kustomize/dev/deployment.yaml
        git add kustomize/dev/deployment.yaml
        git commit -m "[pipeline] deploy new commit ${{ github.sha::7 }}"
        git push origin devops

  build-and-deploy-prod:
    if: github.event_name == 'release' && github.event.action == 'created' && startsWith(github.event.ref, 'refs/tags/production')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and Push Docker Image (Prod)
      run: |
        # echo $PROD_ENV | base64 -d > .env
        # echo $PROD_GCP_KEY > ./gcloud-api-key.json
        # echo $PROD_MYSQL_PROXY_JSON > ./cloudproxy.json

        short_sha=$(echo "${{ github.sha }}" | cut -c1-7)
        docker build -t 425212047113.dkr.ecr.ap-northeast-1.amazonaws.com/influx-website:$short_sha .
        docker push 425212047113.dkr.ecr.ap-northeast-1.amazonaws.com/influx-website:$short_sha

    - name: Update Kustomize Deploy (Prod)
      run: |
        git fetch
        git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
        git fetch origin
        git switch devops

        sed -E -i "s|(image:[^:]+).*|image:\ gcr.io/vr-cam-161603/viewer-backend-v3/viewer-backend-v3-prod:${{ github.ref_name }}|g" kustomize/prod/deployment.yaml
        git add kustomize/prod/deployment.yaml
        git commit -m "[pipeline] deploy new commit ${{ github.ref_name }}"
        git push origin devops
