apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: influx-website-deployment-hpa
  namespace: default
  labels:
    app: influx-website
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: influx-website-deployment
  minReplicas: 2
  maxReplicas: 30
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
