# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: influx-website-service
  namespace: default
  labels:
    app: influx-website
spec:
  selector:
    app: influx-website
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      port: 443
      targetPort: 80
  type: LoadBalancer
  # sessionAffinity: ClientIP
  # sessionAffinityConfig:
  #   clientIP:
  #     timeoutSeconds: 7200
  
