<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

$config['school_major_point']= array(
    '醫藥衛生學門' => 400,
    '教育學門' => 400,
    '運輸服務學門' => 400,
    '資訊通訊科技學門' => 400,
    '工程及工程業學門' => 400,
    '建築及營建工程學門' => 300,
    '商業及管理學門' => 400,
    '物理、化學及地球科學學門' => 300,
    '社會及行為科學學門' => 300,
    '獸醫學門' => 300,
    '數學及統計學門' => 400,
    '法律學門' => 400,
    '安全服務學門' => 200,
    '製造及加工學門' => 200,
    '衛生及職業衛生服務學門' => 300,
    '農業學門' => 200,
    '餐旅及民生服務學門' => 200,
    '環境學門' => 200,
    '人文學門' => 200,
    '語文學門' => 200,
    '社會福利學門' => 200,
    '新聞學及圖書資訊學門' => 200,
    '生命科學學門' => 100,
    '藝術學門(設計學門)' => 200,
    '林業學門' => 100,
    '漁業學門' => 100,
);

$config['school_points']= array(
 ['name' => '國立陽明大學', 'points' => 1600, 'national' => 1],
 ['name' => '國立政治大學', 'points' => 1800, 'national' => 1],
 ['name' => '國立清華大學', 'points' => 1800, 'national' => 1],
 ['name' => '國立臺灣大學', 'points' => 1800, 'national' => 1],
 ['name' => '國立成功大學', 'points' => 1800, 'national' => 1],
 ['name' => '國立交通大學', 'points' => 1800, 'national' => 1],
 ['name' => '國立臺北大學', 'points' => 1600, 'national' => 1],
 ['name' => '臺北醫學大學', 'points' => 1600, 'national' => 0],
 ['name' => '國立臺灣師範大學', 'points' => 1400, 'national' => 1],
 ['name' => '國立中央大學', 'points' => 1600, 'national' => 1],
 ['name' => '國立中山大學', 'points' => 1600, 'national' => 1],
 ['name' => '國立中興大學', 'points' => 1600, 'national' => 1],
 ['name' => '國立中正大學', 'points' => 1600, 'national' => 1],
 ['name' => '馬偕醫學院', 'points' => 1200, 'national' => 0],
 ['name' => '中國醫藥大學', 'points' => 1200, 'national' => 0],
 ['name' => '長庚大學', 'points' => 800, 'national' => 0],
 ['name' => '高雄醫學大學', 'points' => 1000, 'national' => 0],
 ['name' => '國立臺北藝術大學', 'points' => 800, 'national' => 1],
 ['name' => '國立臺灣藝術大學', 'points' => 900, 'national' => 1],
 ['name' => '國立臺北教育大學', 'points' => 1100, 'national' => 1],
 ['name' => '國立彰化師範大學', 'points' => 1100, 'national' => 1],
 ['name' => '臺北市立大學', 'points' => 1100, 'national' => 1],
 ['name' => '國立臺灣科技大學', 'points' => 1400, 'national' => 1],
 ['name' => '國立臺北科技大學', 'points' => 1400, 'national' => 1],
 ['name' => '國立臺北商業大學', 'points' => 1600, 'national' => 1],
 ['name' => '國立高雄大學', 'points' => 800, 'national' => 1],
 ['name' => '輔仁大學', 'points' => 800, 'national' => 0],
 ['name' => '東吳大學', 'points' => 1600, 'national' => 0],
 ['name' => '中山醫學大學', 'points' => 800, 'national' => 0],
 ['name' => '中信金融管理學院', 'points' => 600, 'national' => 0],
 ['name' => '國立雲林科技大學', 'points' => 800, 'national' => 1],
 ['name' => '國立臺中科技大學', 'points' => 800, 'national' => 1],
 ['name' => '國立臺北護理健康大學', 'points' => 800, 'national' => 1],
 ['name' => '國立高雄師範大學', 'points' => 500, 'national' => 1],
 ['name' => '國立臺中教育大學', 'points' => 700, 'national' => 1],
 ['name' => '國立臺灣海洋大學', 'points' => 800, 'national' => 1],
 ['name' => '國立暨南國際大學', 'points' => 700, 'national' => 1],
 ['name' => '國立高雄餐旅大學', 'points' => 800, 'national' => 1],
 ['name' => '國立屏東科技大學', 'points' => 700, 'national' => 1],
 ['name' => '朝陽科技大學', 'points' => 700, 'national' => 0],
 ['name' => '國立臺南護理專科學校', 'points' => 200, 'national' => 1],
 ['name' => '國立臺東專科學校', 'points' => 200, 'national' => 1],
 ['name' => '馬偕醫護管理專科學校', 'points' => 300, 'national' => 0],
 ['name' => '國立臺南大學', 'points' => 500, 'national' => 1],
 ['name' => '國立嘉義大學', 'points' => 700, 'national' => 1],
 ['name' => '國立臺南藝術大學', 'points' => 500, 'national' => 1],
 ['name' => '國立臺灣戲曲學院', 'points' => 300, 'national' => 1],
 ['name' => '淡江大學', 'points' => 900, 'national' => 0],
 ['name' => '長庚科技大學', 'points' => 600, 'national' => 0],
 ['name' => '國立高雄科技大學', 'points' => 1600, 'national' => 1],
 ['name' => '文藻外語大學', 'points' => 600, 'national' => 0],
 ['name' => '耕莘健康管理專科學校', 'points' => 200, 'national' => 0],
 ['name' => '聖母醫護管理專科學校', 'points' => 200, 'national' => 0],
 ['name' => '仁德醫護管理專科學校', 'points' => 200, 'national' => 0],
 ['name' => '世新大學', 'points' => 700, 'national' => 0],
 ['name' => '亞洲大學', 'points' => 300, 'national' => 0],
 ['name' => '中原大學', 'points' => 700, 'national' => 0],
 ['name' => '國立屏東大學', 'points' => 500, 'national' => 1],
 ['name' => '國立東華大學', 'points' => 700, 'national' => 1],
 ['name' => '國立虎尾科技大學', 'points' => 700, 'national' => 1],
 ['name' => '國立勤益科技大學', 'points' => 200, 'national' => 1],
 ['name' => '致理科技大學', 'points' => 200, 'national' => 0],
 ['name' => '明志科技大學', 'points' => 200, 'national' => 0],
 ['name' => '育英醫護管理專科學校', 'points' => 100, 'national' => 0],
 ['name' => '崇仁醫護管理專科學校', 'points' => 100, 'national' => 0],
 ['name' => '新生醫護管理專科學校', 'points' => 100, 'national' => 0],
 ['name' => '樹人醫護管理專科學校', 'points' => 0, 'national' => 0],
 ['name' => '慈惠醫護管理專科學校', 'points' => 0, 'national' => 0],
 ['name' => '敏惠醫護管理專科學校', 'points' => 0, 'national' => 0],
 ['name' => '高美醫護管理專科學校', 'points' => 0, 'national' => 0],
 ['name' => '元智大學', 'points' => 800, 'national' => 0],
 ['name' => '國立宜蘭大學', 'points' => 500, 'national' => 1],
 ['name' => '銘傳大學', 'points' => 800, 'national' => 0],
 ['name' => '逢甲大學', 'points' => 700, 'national' => 0],
 ['name' => '東海大學', 'points' => 600, 'national' => 0],
 ['name' => '靜宜大學', 'points' => 400, 'national' => 0],
 ['name' => '國立臺灣體育運動大學', 'points' => 300, 'national' => 1],
 ['name' => '國立體育大學', 'points' => 300, 'national' => 1],
 ['name' => '國立臺東大學', 'points' => 200, 'national' => 1],
 ['name' => '中國文化大學', 'points' => 400, 'national' => 0],
 ['name' => '南臺科技大學', 'points' => 100, 'national' => 0],
 ['name' => '國立澎湖科技大學', 'points' => 300, 'national' => 1],
 ['name' => '僑光科技大學', 'points' => 100, 'national' => 0],
 ['name' => '臺南應用科技大學', 'points' => 100, 'national' => 0],
 ['name' => '實踐大學', 'points' => 600, 'national' => 0],
 ['name' => '國立金門大學', 'points' => 300, 'national' => 1],
 ['name' => '國立聯合大學', 'points' => 200, 'national' => 1],
 ['name' => '大同大學', 'points' => 300, 'national' => 0],
 ['name' => '慈濟大學', 'points' => 0, 'national' => 0],
 ['name' => '義守大學', 'points' => 0, 'national' => 0],
 ['name' => '佛光大學', 'points' => 0, 'national' => 0],
 ['name' => '長榮大學', 'points' => 200, 'national' => 0],
 ['name' => '玄奘大學', 'points' => 200, 'national' => 0],
 ['name' => '大葉大學', 'points' => 0, 'national' => 0],
 ['name' => '南華大學', 'points' => 0, 'national' => 0],
 ['name' => '法鼓文理學院', 'points' => 100, 'national' => 0],
 ['name' => '弘光科技大學', 'points' => 0, 'national' => 0],
 ['name' => '嶺東科技大學', 'points' => 100, 'national' => 0],
 ['name' => '德明財經科技大學', 'points' => 0, 'national' => 0],
 ['name' => '中臺科技大學', 'points' => 200, 'national' => 0],
 ['name' => '臺北海洋科技大學', 'points' => 0, 'national' => 0],
 ['name' => '亞太創意技術學院', 'points' => 100, 'national' => 0],
 ['name' => '龍華科技大學', 'points' => 0, 'national' => 0],
 ['name' => '明新科技大學', 'points' => 200, 'national' => 0],
 ['name' => '聖約翰科技大學', 'points' => 100, 'national' => 0],
 ['name' => '中華大學', 'points' => 0, 'national' => 0],
 ['name' => '華梵大學', 'points' => 0, 'national' => 0],
 ['name' => '真理大學', 'points' => 0, 'national' => 0],
 ['name' => '開南大學', 'points' => 0, 'national' => 0],
 ['name' => '明道大學', 'points' => 0, 'national' => 0],
 ['name' => '臺灣首府大學', 'points' => 0, 'national' => 0],
 ['name' => '康寧大學', 'points' => 0, 'national' => 0],
 ['name' => '稻江科技暨管理學院', 'points' => 0, 'national' => 0],
 ['name' => '崑山科技大學', 'points' => 0, 'national' => 0],
 ['name' => '嘉南藥理大學', 'points' => 0, 'national' => 0],
 ['name' => '樹德科技大學', 'points' => 0, 'national' => 0],
 ['name' => '輔英科技大學', 'points' => 100, 'national' => 0],
 ['name' => '健行科技大學', 'points' => 100, 'national' => 0],
 ['name' => '正修科技大學', 'points' => 0, 'national' => 0],
 ['name' => '萬能科技大學', 'points' => 0, 'national' => 0],
 ['name' => '建國科技大學', 'points' => 0, 'national' => 0],
 ['name' => '高苑科技大學', 'points' => 0, 'national' => 0],
 ['name' => '大仁科技大學', 'points' => 0, 'national' => 0],
 ['name' => '中國科技大學', 'points' => 100, 'national' => 0],
 ['name' => '遠東科技大學', 'points' => 0, 'national' => 0],
 ['name' => '元培醫事科技大學', 'points' => 200, 'national' => 0],
 ['name' => '景文科技大學', 'points' => 0, 'national' => 0],
 ['name' => '中華醫事科技大學', 'points' => 100, 'national' => 0],
 ['name' => '東南科技大學', 'points' => 0, 'national' => 0],
 ['name' => '南開科技大學', 'points' => 100, 'national' => 0],
 ['name' => '中華科技大學', 'points' => 0, 'national' => 0],
 ['name' => '育達科技大學', 'points' => 0, 'national' => 0],
 ['name' => '美和科技大學', 'points' => 0, 'national' => 0],
 ['name' => '吳鳳科技大學', 'points' => 0, 'national' => 0],
 ['name' => '環球科技大學', 'points' => 0, 'national' => 0],
 ['name' => '中州科技大學', 'points' => 0, 'national' => 0],
 ['name' => '修平科技大學', 'points' => 0, 'national' => 0],
 ['name' => '臺北城市科技大學', 'points' => 100, 'national' => 0],
 ['name' => '大華科技大學', 'points' => 0, 'national' => 0],
 ['name' => '醒吾科技大學', 'points' => 0, 'national' => 0],
 ['name' => '南榮科技大學', 'points' => 0, 'national' => 0],
 ['name' => '華夏科技大學', 'points' => 0, 'national' => 0],
 ['name' => '慈濟科技大學', 'points' => 200, 'national' => 0],
 ['name' => '宏國德霖科技大學', 'points' => 0, 'national' => 0],
 ['name' => '東方設計大學', 'points' => 0, 'national' => 0],
 ['name' => '崇右影藝科技大學', 'points' => 100, 'national' => 0],
 ['name' => '大漢技術學院', 'points' => 0, 'national' => 0],
 ['name' => '和春技術學院', 'points' => 0, 'national' => 0],
 ['name' => '亞東技術學院', 'points' => 200, 'national' => 0],
 ['name' => '南亞技術學院', 'points' => 0, 'national' => 0],
 ['name' => '蘭陽技術學院', 'points' => 0, 'national' => 0],
 ['name' => '黎明技術學院', 'points' => 0, 'national' => 0],
 ['name' => '經國管理暨健康學院', 'points' => 100, 'national' => 0],
 ['name' => '大同技術學院', 'points' => 0, 'national' => 0],
 ['name' => '臺灣觀光學院', 'points' => 0, 'national' => 0],
);
